function f(a){throw a;}var j=void 0,k=!0,m=null,o=!1;function aa(a){return function(){return this[a]}}function q(a){return function(){return a}}var r,ba=this;function ca(){}
function da(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function t(a){return a!==j}function ea(a){var b=da(a);return"array"==b||"object"==b&&"number"==typeof a.length}function u(a){return"string"==typeof a}function fa(a){return"number"==typeof a}function ga(a){var b=typeof a;return"object"==b&&a!=m||"function"==b}Math.floor(2147483648*Math.random()).toString(36);function ha(a,b,c){return a.call.apply(a.bind,arguments)}
function ia(a,b,c){a||f(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function v(a,b,c){v=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ha:ia;return v.apply(m,arguments)}function ja(a,b){function c(){}c.prototype=b.prototype;a.Td=b.prototype;a.prototype=new c};function ka(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}f(Error("Invalid JSON string: "+a))}function la(){this.ic=j}
function ma(a,b,c){switch(typeof b){case "string":na(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==m){c.push("null");break}if("array"==da(b)){var d=b.length;c.push("[");for(var e="",g=0;g<d;g++)c.push(e),e=b[g],ma(a,a.ic?a.ic.call(b,String(g),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(g in b)Object.prototype.hasOwnProperty.call(b,g)&&(e=b[g],"function"!=typeof e&&(c.push(d),
na(g,c),c.push(":"),ma(a,a.ic?a.ic.call(b,g,e):e,c),d=","));c.push("}");break;case "function":break;default:f(Error("Unknown type: "+typeof b))}}var oa={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},pa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function na(a,b){b.push('"',a.replace(pa,function(a){if(a in oa)return oa[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return oa[a]=e+b.toString(16)}),'"')};function qa(a){return"undefined"!==typeof JSON&&t(JSON.parse)?JSON.parse(a):ka(a)}function y(a){if("undefined"!==typeof JSON&&t(JSON.stringify))a=JSON.stringify(a);else{var b=[];ma(new la,a,b);a=b.join("")}return a};function ra(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);55296<=e&&56319>=e&&(e-=55296,d++,z(d<a.length,"Surrogate pair missing trail surrogate."),e=65536+(e<<10)+(a.charCodeAt(d)-56320));128>e?b[c++]=e:(2048>e?b[c++]=e>>6|192:(65536>e?b[c++]=e>>12|224:(b[c++]=e>>18|240,b[c++]=e>>12&63|128),b[c++]=e>>6&63|128),b[c++]=e&63|128)}return b};function A(a,b,c,d){var e;d<b?e="at least "+b:d>c&&(e=0===c?"none":"no more than "+c);e&&f(Error(a+" failed: Was called with "+d+(1===d?" argument.":" arguments.")+" Expects "+e+"."))}function B(a,b,c){var d="";switch(b){case 1:d=c?"first":"First";break;case 2:d=c?"second":"Second";break;case 3:d=c?"third":"Third";break;case 4:d=c?"fourth":"Fourth";break;default:sa.assert(o,"errorPrefix_ called with argumentNumber > 4.  Need to update it?")}return a+" failed: "+(d+" argument ")}
function C(a,b,c,d){(!d||t(c))&&"function"!=da(c)&&f(Error(B(a,b,d)+"must be a valid function."))}function ta(a,b,c){t(c)&&(!ga(c)||c===m)&&f(Error(B(a,b,k)+"must be a valid context object."))};function D(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function ua(a,b){if(Object.prototype.hasOwnProperty.call(a,b))return a[b]};var va={},sa={},wa=/[\[\].#$\/]/,xa=/[\[\].#$]/;function ya(a){return u(a)&&0!==a.length&&!wa.test(a)}function za(a,b,c){(!c||t(b))&&Aa(B(a,1,c),b)}
function Aa(a,b,c,d){c||(c=0);d||(d=[]);t(b)||f(Error(a+"contains undefined"+Ba(d)));"function"==da(b)&&f(Error(a+"contains a function"+Ba(d)+" with contents: "+b.toString()));Ca(b)&&f(Error(a+"contains "+b.toString()+Ba(d)));1E3<c&&f(new TypeError(a+"contains a cyclic object value ("+d.slice(0,100).join(".")+"...)"));u(b)&&(b.length>10485760/3&&10485760<va.Ud.Sd(b).length)&&f(Error(a+"contains a string greater than 10485760 utf8 bytes"+Ba(d)+" ('"+b.substring(0,50)+"...')"));if(ga(b))for(var e in b)D(b,
e)&&(".priority"!==e&&(".value"!==e&&!ya(e))&&f(Error(a+"contains an invalid key ("+e+")"+Ba(d)+'.  Keys must be non-empty strings and can\'t contain ".", "#", "$", "/", "[", or "]"')),d.push(e),Aa(a,b[e],c+1,d),d.pop())}function Ba(a){return 0==a.length?"":" in property '"+a.join(".")+"'"}function Da(a,b){ga(b)||f(Error(B(a,1,o)+" must be an object containing the children to replace."));za(a,b,o)}
function Ea(a,b,c,d){(!d||t(c))&&(c!==m&&!fa(c)&&!u(c))&&f(Error(B(a,b,d)+"must be a valid firebase priority (null or a string.)"))}function Fa(a,b,c){if(!c||t(b))switch(b){case "value":case "child_added":case "child_removed":case "child_changed":case "child_moved":break;default:f(Error(B(a,1,c)+'must be a valid event type: "value", "child_added", "child_removed", "child_changed", or "child_moved".'))}}
function Ga(a,b){t(b)&&!ya(b)&&f(Error(B(a,2,k)+'must be a valid firebase key (non-empty string, not containing ".", "#", "$", "/", "[", or "]").'))}function Ha(a,b){(!u(b)||0===b.length||xa.test(b))&&f(Error(B(a,1,o)+'must be a non-empty string and can\'t contain ".", "#", "$", "[", or "]".'))}function E(a,b){".info"===F(b)&&f(Error(a+" failed: Can't modify data under /.info/"))};function G(a,b,c,d,e,g,h){this.w=a;this.path=b;this.xa=c;this.ga=d;this.ra=e;this.va=g;this.Ua=h;t(this.ga)&&(t(this.va)&&t(this.xa))&&f("Query: Can't combine startAt(), endAt(), and limit().")}G.prototype.vc=function(a,b){A("Query.on",2,4,arguments.length);Fa("Query.on",a,o);C("Query.on",2,b,o);var c=Ia("Query.on",arguments[2],arguments[3]);this.w.Lb(this,a,b,c.cancel,c.aa);return b};G.prototype.on=G.prototype.vc;
G.prototype.Ub=function(a,b,c){A("Query.off",0,3,arguments.length);Fa("Query.off",a,k);C("Query.off",2,b,k);ta("Query.off",3,c);this.w.hc(this,a,b,c)};G.prototype.off=G.prototype.Ub;G.prototype.Dd=function(a,b){function c(h){g&&(g=o,e.Ub(a,c),b.call(d.aa,h))}A("Query.once",2,4,arguments.length);Fa("Query.once",a,o);C("Query.once",2,b,o);var d=Ia("Query.once",arguments[2],arguments[3]),e=this,g=k;this.vc(a,c,function(){e.Ub(a,c);d.cancel&&d.cancel.call(d.aa)})};G.prototype.once=G.prototype.Dd;
G.prototype.Ad=function(a){A("Query.limit",1,1,arguments.length);(!fa(a)||Math.floor(a)!==a||0>=a)&&f("Query.limit: First argument must be a positive integer.");return new G(this.w,this.path,a,this.ga,this.ra,this.va,this.Ua)};G.prototype.limit=G.prototype.Ad;G.prototype.Nd=function(a,b){A("Query.startAt",0,2,arguments.length);Ea("Query.startAt",1,a,k);Ga("Query.startAt",b);t(a)||(b=a=m);return new G(this.w,this.path,this.xa,a,b,this.va,this.Ua)};G.prototype.startAt=G.prototype.Nd;
G.prototype.ud=function(a,b){A("Query.endAt",0,2,arguments.length);Ea("Query.endAt",1,a,k);Ga("Query.endAt",b);return new G(this.w,this.path,this.xa,this.ga,this.ra,a,b)};G.prototype.endAt=G.prototype.ud;function Ja(a){var b={};t(a.ga)&&(b.sp=a.ga);t(a.ra)&&(b.sn=a.ra);t(a.va)&&(b.ep=a.va);t(a.Ua)&&(b.en=a.Ua);t(a.xa)&&(b.l=a.xa);t(a.ga)&&(t(a.ra)&&a.ga===m&&a.ra===m)&&(b.vf="l");return b}G.prototype.La=function(){var a=Ka(Ja(this));return"{}"===a?"default":a};
function Ia(a,b,c){var d={};b&&c?(d.cancel=b,C(a,3,d.cancel,k),d.aa=c,ta(a,4,d.aa)):b&&("object"===typeof b&&b!==m?d.aa=b:"function"===typeof b?d.cancel=b:f(Error(B(a,3,k)+"must either be a cancel callback or a context object.")));return d};function I(a){if(a instanceof I)return a;if(1==arguments.length){this.m=a.split("/");for(var b=0,c=0;c<this.m.length;c++)0<this.m[c].length&&(this.m[b]=this.m[c],b++);this.m.length=b;this.ea=0}else this.m=arguments[0],this.ea=arguments[1]}function F(a){return a.ea>=a.m.length?m:a.m[a.ea]}function J(a){var b=a.ea;b<a.m.length&&b++;return new I(a.m,b)}function La(a){return a.ea<a.m.length?a.m[a.m.length-1]:m}r=I.prototype;
r.toString=function(){for(var a="",b=this.ea;b<this.m.length;b++)""!==this.m[b]&&(a+="/"+this.m[b]);return a||"/"};r.parent=function(){if(this.ea>=this.m.length)return m;for(var a=[],b=this.ea;b<this.m.length-1;b++)a.push(this.m[b]);return new I(a,0)};r.F=function(a){for(var b=[],c=this.ea;c<this.m.length;c++)b.push(this.m[c]);if(a instanceof I)for(c=a.ea;c<a.m.length;c++)b.push(a.m[c]);else{a=a.split("/");for(c=0;c<a.length;c++)0<a[c].length&&b.push(a[c])}return new I(b,0)};
r.f=function(){return this.ea>=this.m.length};function Ma(a,b){var c=F(a);if(c===m)return b;if(c===F(b))return Ma(J(a),J(b));f("INTERNAL ERROR: innerPath ("+b+") is not within outerPath ("+a+")")}r.contains=function(a){var b=0;if(this.m.length>a.m.length)return o;for(;b<this.m.length;){if(this.m[b]!==a.m[b])return o;++b}return k};function Na(){this.children={};this.Nb=0;this.value=m}function Oa(a,b,c){this.ya=a?a:"";this.wb=b?b:m;this.u=c?c:new Na}function L(a,b){for(var c=b instanceof I?b:new I(b),d=a,e;(e=F(c))!==m;)d=new Oa(e,d,ua(d.u.children,e)||new Na),c=J(c);return d}r=Oa.prototype;r.j=function(){return this.u.value};function M(a,b){z("undefined"!==typeof b);a.u.value=b;Pa(a)}r.clear=function(){this.u.value=m;this.u.children={};this.u.Nb=0;Pa(this)};r.mb=function(){return 0<this.u.Nb};
r.f=function(){return this.j()===m&&!this.mb()};r.z=function(a){for(var b in this.u.children)a(new Oa(b,this,this.u.children[b]))};function Qa(a,b,c,d){c&&!d&&b(a);a.z(function(a){Qa(a,b,k,d)});c&&d&&b(a)}function Ra(a,b,c){for(a=c?a:a.parent();a!==m;){if(b(a))return k;a=a.parent()}return o}r.path=function(){return new I(this.wb===m?this.ya:this.wb.path()+"/"+this.ya)};r.name=aa("ya");r.parent=aa("wb");
function Pa(a){if(a.wb!==m){var b=a.wb,c=a.ya,d=a.f(),e=D(b.u.children,c);d&&e?(delete b.u.children[c],b.u.Nb--,Pa(b)):!d&&!e&&(b.u.children[c]=a.u,b.u.Nb++,Pa(b))}};function Ua(a,b){this.Ra=a?a:Va;this.fa=b?b:Wa}function Va(a,b){return a<b?-1:a>b?1:0}r=Ua.prototype;r.oa=function(a,b){return new Ua(this.Ra,this.fa.oa(a,b,this.Ra).copy(m,m,o,m,m))};r.remove=function(a){return new Ua(this.Ra,this.fa.remove(a,this.Ra).copy(m,m,o,m,m))};r.get=function(a){for(var b,c=this.fa;!c.f();){b=this.Ra(a,c.key);if(0===b)return c.value;0>b?c=c.left:0<b&&(c=c.right)}return m};
function Xa(a,b){for(var c,d=a.fa,e=m;!d.f();){c=a.Ra(b,d.key);if(0===c){if(d.left.f())return e?e.key:m;for(d=d.left;!d.right.f();)d=d.right;return d.key}0>c?d=d.left:0<c&&(e=d,d=d.right)}f(Error("Attempted to find predecessor key for a nonexistent key.  What gives?"))}r.f=function(){return this.fa.f()};r.count=function(){return this.fa.count()};r.rb=function(){return this.fa.rb()};r.Xa=function(){return this.fa.Xa()};r.wa=function(a){return this.fa.wa(a)};r.Ma=function(a){return this.fa.Ma(a)};
r.Va=function(a){return new Ya(this.fa,a)};function Ya(a,b){this.dd=b;for(this.Sb=[];!a.f();)this.Sb.push(a),a=a.left}function Za(a){if(0===a.Sb.length)return m;var b=a.Sb.pop(),c;c=a.dd?a.dd(b.key,b.value):{key:b.key,value:b.value};for(b=b.right;!b.f();)a.Sb.push(b),b=b.left;return c}function $a(a,b,c,d,e){this.key=a;this.value=b;this.color=c!=m?c:k;this.left=d!=m?d:Wa;this.right=e!=m?e:Wa}r=$a.prototype;
r.copy=function(a,b,c,d,e){return new $a(a!=m?a:this.key,b!=m?b:this.value,c!=m?c:this.color,d!=m?d:this.left,e!=m?e:this.right)};r.count=function(){return this.left.count()+1+this.right.count()};r.f=q(o);r.wa=function(a){return this.left.wa(a)||a(this.key,this.value)||this.right.wa(a)};r.Ma=function(a){return this.right.Ma(a)||a(this.key,this.value)||this.left.Ma(a)};function ab(a){return a.left.f()?a:ab(a.left)}r.rb=function(){return ab(this).key};
r.Xa=function(){return this.right.f()?this.key:this.right.Xa()};r.oa=function(a,b,c){var d,e;e=this;d=c(a,e.key);e=0>d?e.copy(m,m,m,e.left.oa(a,b,c),m):0===d?e.copy(m,b,m,m,m):e.copy(m,m,m,m,e.right.oa(a,b,c));return bb(e)};function cb(a){if(a.left.f())return Wa;!a.left.M()&&!a.left.left.M()&&(a=db(a));a=a.copy(m,m,m,cb(a.left),m);return bb(a)}
r.remove=function(a,b){var c,d;c=this;if(0>b(a,c.key))!c.left.f()&&(!c.left.M()&&!c.left.left.M())&&(c=db(c)),c=c.copy(m,m,m,c.left.remove(a,b),m);else{c.left.M()&&(c=eb(c));!c.right.f()&&(!c.right.M()&&!c.right.left.M())&&(c=fb(c),c.left.left.M()&&(c=eb(c),c=fb(c)));if(0===b(a,c.key)){if(c.right.f())return Wa;d=ab(c.right);c=c.copy(d.key,d.value,m,m,cb(c.right))}c=c.copy(m,m,m,m,c.right.remove(a,b))}return bb(c)};r.M=aa("color");
function bb(a){a.right.M()&&!a.left.M()&&(a=gb(a));a.left.M()&&a.left.left.M()&&(a=eb(a));a.left.M()&&a.right.M()&&(a=fb(a));return a}function db(a){a=fb(a);a.right.left.M()&&(a=a.copy(m,m,m,m,eb(a.right)),a=gb(a),a=fb(a));return a}function gb(a){var b;b=a.copy(m,m,k,m,a.right.left);return a.right.copy(m,m,a.color,b,m)}function eb(a){var b;b=a.copy(m,m,k,a.left.right,m);return a.left.copy(m,m,a.color,m,b)}
function fb(a){var b,c;b=a.left.copy(m,m,!a.left.color,m,m);c=a.right.copy(m,m,!a.right.color,m,m);return a.copy(m,m,!a.color,b,c)}function hb(){}r=hb.prototype;r.copy=function(){return this};r.oa=function(a,b){return new $a(a,b,j,j,j)};r.remove=function(){return this};r.get=q(m);r.count=q(0);r.f=q(k);r.wa=q(o);r.Ma=q(o);r.rb=q(m);r.Xa=q(m);r.M=q(o);var Wa=new hb;var ib=Array.prototype,jb=ib.forEach?function(a,b,c){ib.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=u(a)?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)},kb=ib.map?function(a,b,c){return ib.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),g=u(a)?a.split(""):a,h=0;h<d;h++)h in g&&(e[h]=b.call(c,g[h],h,a));return e};function lb(){};function mb(){this.B=[];this.pc=[];this.qd=[];this.$b=[];this.$b[0]=128;for(var a=1;64>a;++a)this.$b[a]=0;this.reset()}ja(mb,lb);mb.prototype.reset=function(){this.B[0]=1732584193;this.B[1]=4023233417;this.B[2]=2562383102;this.B[3]=271733878;this.B[4]=3285377520;this.Jc=this.nb=0};
function nb(a,b){var c;c||(c=0);for(var d=a.qd,e=c;e<c+64;e+=4)d[e/4]=b[e]<<24|b[e+1]<<16|b[e+2]<<8|b[e+3];for(e=16;80>e;e++){var g=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(g<<1|g>>>31)&4294967295}c=a.B[0];for(var h=a.B[1],i=a.B[2],l=a.B[3],n=a.B[4],p,e=0;80>e;e++)40>e?20>e?(g=l^h&(i^l),p=1518500249):(g=h^i^l,p=1859775393):60>e?(g=h&i|l&(h|i),p=2400959708):(g=h^i^l,p=3395469782),g=(c<<5|c>>>27)+g+n+p+d[e]&4294967295,n=l,l=i,i=(h<<30|h>>>2)&4294967295,h=c,c=g;a.B[0]=a.B[0]+c&4294967295;a.B[1]=a.B[1]+h&
4294967295;a.B[2]=a.B[2]+i&4294967295;a.B[3]=a.B[3]+l&4294967295;a.B[4]=a.B[4]+n&4294967295}mb.prototype.update=function(a,b){t(b)||(b=a.length);var c=this.pc,d=this.nb,e=0;if(u(a))for(;e<b;)c[d++]=a.charCodeAt(e++),64==d&&(nb(this,c),d=0);else for(;e<b;)c[d++]=a[e++],64==d&&(nb(this,c),d=0);this.nb=d;this.Jc+=b};function ob(){this.Qa={};this.length=0}ob.prototype.setItem=function(a,b){D(this.Qa,a)||(this.length+=1);this.Qa[a]=b};ob.prototype.getItem=function(a){return D(this.Qa,a)?this.Qa[a]:m};ob.prototype.removeItem=function(a){D(this.Qa,a)&&(this.length-=1,delete this.Qa[a])};var O=m;if("undefined"!==typeof sessionStorage)try{sessionStorage.setItem("firebase-sentinel","cache"),sessionStorage.removeItem("firebase-sentinel"),O=sessionStorage}catch(pb){O=new ob}else O=new ob;function qb(a,b,c,d){this.host=a;this.Eb=b;this.Ya=c;this.T=d||O.getItem(a)||this.host}function rb(a,b){b!==a.T&&(a.T=b,"s-"===a.T.substr(0,2)&&O.setItem(a.host,a.T))}qb.prototype.toString=function(){return(this.Eb?"https://":"http://")+this.host};var sb,tb,ub,vb;function wb(){return ba.navigator?ba.navigator.userAgent:m}vb=ub=tb=sb=o;var xb;if(xb=wb()){var yb=ba.navigator;sb=0==xb.indexOf("Opera");tb=!sb&&-1!=xb.indexOf("MSIE");ub=!sb&&-1!=xb.indexOf("WebKit");vb=!sb&&!ub&&"Gecko"==yb.product}var zb=tb,Ab=vb,Bb=ub;var Cb;if(sb&&ba.opera){var Db=ba.opera.version;"function"==typeof Db&&Db()}else Ab?Cb=/rv\:([^\);]+)(\)|;)/:zb?Cb=/MSIE\s+([^\);]+)(\)|;)/:Bb&&(Cb=/WebKit\/(\S+)/),Cb&&Cb.exec(wb());var Eb=m,Fb=m;
function Gb(a,b){ea(a)||f(Error("encodeByteArray takes an array as a parameter"));if(!Eb){Eb={};Fb={};for(var c=0;65>c;c++)Eb[c]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c),Fb[c]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(c)}for(var c=b?Fb:Eb,d=[],e=0;e<a.length;e+=3){var g=a[e],h=e+1<a.length,i=h?a[e+1]:0,l=e+2<a.length,n=l?a[e+2]:0,p=g>>2,g=(g&3)<<4|i>>4,i=(i&15)<<2|n>>6,n=n&63;l||(n=64,h||(i=64));d.push(c[p],c[g],c[i],c[n])}return d.join("")}
;var Hb,Ib=1;Hb=function(){return Ib++};function z(a,b){a||f(Error("Firebase INTERNAL ASSERT FAILED:"+b))}function Jb(a){a=ra(a);return Gb(a,k)}function Kb(a){var b=ra(a),a=new mb;a.update(b);var b=[],c=8*a.Jc;56>a.nb?a.update(a.$b,56-a.nb):a.update(a.$b,64-(a.nb-56));for(var d=63;56<=d;d--)a.pc[d]=c&255,c/=256;nb(a,a.pc);for(d=c=0;5>d;d++)for(var e=24;0<=e;e-=8)b[c++]=a.B[d]>>e&255;return Gb(b)}
function Lb(){for(var a="",b=0;b<arguments.length;b++)a=ea(arguments[b])?a+Lb.apply(m,arguments[b]):"object"===typeof arguments[b]?a+y(arguments[b]):a+arguments[b],a+=" ";return a}var Mb=m,Nb=k;function Ob(){Nb===k&&(Nb=o,Mb===m&&"true"===O.getItem("logging_enabled")&&Pb(k));if(Mb){var a=Lb.apply(m,arguments);Mb(a)}}function Qb(a){return function(){Ob(a,arguments)}}
function Rb(){if("undefined"!==typeof console){var a="FIREBASE INTERNAL ERROR: "+Lb.apply(m,arguments);"undefined"!==typeof console.error?console.error(a):console.log(a)}}function Sb(){var a=Lb.apply(m,arguments);f(Error("FIREBASE FATAL ERROR: "+a))}function Tb(){if("undefined"!==typeof console){var a="FIREBASE WARNING: "+Lb.apply(m,arguments);"undefined"!==typeof console.warn?console.warn(a):console.log(a)}}
function Ca(a){return fa(a)&&(a!=a||a==Number.POSITIVE_INFINITY||a==Number.NEGATIVE_INFINITY)}function Ub(a,b){return a!==b?a===m?-1:b===m?1:typeof a!==typeof b?"number"===typeof a?-1:1:a>b?1:-1:0}function Vb(a,b){if(b&&a in b)return b[a];f(Error("Missing required key ("+a+") in object: "+y(b)))}var Wb=0;function Ka(a){if("object"!==typeof a||a===m)return y(a);var b=[],c;for(c in a)b.push(c);b.sort();c="{";for(var d=0;d<b.length;d++)0!==d&&(c+=","),c+=y(b[d]),c+=":",c+=Ka(a[b[d]]);return c+"}"}
function Xb(a,b){if(a.length<=b)return[a];for(var c=[],d=0;d<a.length;d+=b)d+b>a?c.push(a.substring(d,a.length)):c.push(a.substring(d,d+b));return c}
function Yb(a){z(!Ca(a));var b,c,d,e;0===a?(d=c=0,b=-Infinity===1/a?1:0):(b=0>a,a=Math.abs(a),a>=Math.pow(2,-1022)?(d=Math.min(Math.floor(Math.log(a)/Math.LN2),1023),c=d+1023,d=Math.round(a*Math.pow(2,52-d)-Math.pow(2,52))):(c=0,d=Math.round(a/Math.pow(2,-1074))));e=[];for(a=52;a;a-=1)e.push(d%2?1:0),d=Math.floor(d/2);for(a=11;a;a-=1)e.push(c%2?1:0),c=Math.floor(c/2);e.push(b?1:0);e.reverse();b=e.join("");c="";for(a=0;64>a;a+=8)d=parseInt(b.substr(a,8),2).toString(16),1===d.length&&(d="0"+d),c+=d;
return c.toLowerCase()};function Zb(a,b){this.D=a;z(this.D!==m,"LeafNode shouldn't be created with null value.");this.Za="undefined"!==typeof b?b:m}r=Zb.prototype;r.L=q(k);r.k=aa("Za");r.Jb=function(a){return new Zb(this.D,a)};r.S=function(){return P};r.J=function(a){return F(a)===m?this:P};r.Y=q(m);r.I=function(a,b){return(new Q(new Ua,this.Za)).I(a,b)};r.Fa=function(a,b){var c=F(a);return c===m?b:this.I(c,P.Fa(J(a),b))};r.f=q(o);r.Tb=q(0);
r.W=function(a){return a&&this.k()!==m?{".value":this.j(),".priority":this.k()}:this.j()};r.hash=function(){var a="";this.k()!==m&&(a+="priority:"+ac(this.k())+":");var b=typeof this.D,a=a+(b+":"),a="number"===b?a+Yb(this.D):a+this.D;return Kb(a)};r.j=aa("D");r.toString=function(){return"string"===typeof this.D?'"'+this.D+'"':this.D};function Q(a,b){this.n=a||new Ua;this.Za="undefined"!==typeof b?b:m}r=Q.prototype;r.L=q(o);r.k=aa("Za");r.Jb=function(a){return new Q(this.n,a)};r.I=function(a,b){var c=this.n.remove(a);b&&b.f()&&(b=m);b!==m&&(c=c.oa(a,b));return b&&b.k()!==m?new bc(c,m,this.Za):new Q(c,this.Za)};r.Fa=function(a,b){var c=F(a);if(c===m)return b;var d=this.S(c).Fa(J(a),b);return this.I(c,d)};r.f=function(){return this.n.f()};r.Tb=function(){return this.n.count()};var cc=/^\d+$/;r=Q.prototype;
r.W=function(a){if(this.f())return m;var b={},c=0,d=0,e=k;this.z(function(g,h){b[g]=h.W(a);c++;e&&cc.test(g)?d=Math.max(d,Number(g)):e=o});if(!a&&e&&d<2*c){var g=[],h;for(h in b)g[h]=b[h];return g}a&&this.k()!==m&&(b[".priority"]=this.k());return b};r.hash=function(){var a="";this.k()!==m&&(a+="priority:"+ac(this.k())+":");this.z(function(b,c){var d=c.hash();""!==d&&(a+=":"+b+":"+d)});return""===a?"":Kb(a)};r.S=function(a){a=this.n.get(a);return a===m?P:a};
r.J=function(a){var b=F(a);return b===m?this:this.S(b).J(J(a))};r.Y=function(a){return Xa(this.n,a)};r.Rc=function(){return this.n.rb()};r.Sc=function(){return this.n.Xa()};r.z=function(a){return this.n.wa(a)};r.rc=function(a){return this.n.Ma(a)};r.Va=function(){return this.n.Va()};r.toString=function(){var a="{",b=k;this.z(function(c,d){b?b=o:a+=", ";a+='"'+c+'" : '+d.toString()});return a+="}"};var P=new Q(new Ua);function bc(a,b,c){Q.call(this,a,c);b===m&&(b=new Ua(dc),a.wa(function(a,c){b=b.oa({name:a,Aa:c.k()},c)}));this.qa=b}ja(bc,Q);r=bc.prototype;r.I=function(a,b){var c=this.S(a),d=this.n,e=this.qa;c!==m&&(d=d.remove(a),e=e.remove({name:a,Aa:c.k()}));b&&b.f()&&(b=m);b!==m&&(d=d.oa(a,b),e=e.oa({name:a,Aa:b.k()},b));return new bc(d,e,this.k())};r.Y=function(a,b){var c=Xa(this.qa,{name:a,Aa:b.k()});return c?c.name:m};r.z=function(a){return this.qa.wa(function(b,c){return a(b.name,c)})};
r.rc=function(a){return this.qa.Ma(function(b,c){return a(b.name,c)})};r.Va=function(){return this.qa.Va(function(a,b){return{key:a.name,value:b}})};r.Rc=function(){return this.qa.f()?m:this.qa.rb().name};r.Sc=function(){return this.qa.f()?m:this.qa.Xa().name};function R(a,b){if("object"!==typeof a)return new Zb(a,b);if(a===m)return P;var c=m;".priority"in a?c=a[".priority"]:"undefined"!==typeof b&&(c=b);z(c===m||"string"===typeof c||"number"===typeof c);if(".value"in a&&a[".value"]!==m)return new Zb(a[".value"],c);var c=new Q(new Ua,c),d;for(d in a)if(D(a,d)&&"."!==d.substring(0,1)){var e=R(a[d]);if(e.L()||!e.f())c=c.I(d,e)}return c}function dc(a,b){return Ub(a.Aa,b.Aa)||(a.name!==b.name?a.name<b.name?-1:1:0)}
function ac(a){return"number"===typeof a?"number:"+Yb(a):"string:"+a};function S(a,b){this.u=a;this.gc=b}S.prototype.W=function(){A("Firebase.DataSnapshot.val",0,0,arguments.length);return this.u.W()};S.prototype.val=S.prototype.W;S.prototype.vd=function(){A("Firebase.DataSnapshot.exportVal",0,0,arguments.length);return this.u.W(k)};S.prototype.exportVal=S.prototype.vd;S.prototype.F=function(a){A("Firebase.DataSnapshot.child",0,1,arguments.length);fa(a)&&(a=String(a));Ha("Firebase.DataSnapshot.child",a);var b=new I(a),c=this.gc.F(b);return new S(this.u.J(b),c)};
S.prototype.child=S.prototype.F;S.prototype.sc=function(a){A("Firebase.DataSnapshot.hasChild",1,1,arguments.length);Ha("Firebase.DataSnapshot.hasChild",a);var b=new I(a);return!this.u.J(b).f()};S.prototype.hasChild=S.prototype.sc;S.prototype.k=function(){A("Firebase.DataSnapshot.getPriority",0,0,arguments.length);return this.u.k()};S.prototype.getPriority=S.prototype.k;
S.prototype.forEach=function(a){A("Firebase.DataSnapshot.forEach",1,1,arguments.length);C("Firebase.DataSnapshot.forEach",1,a,o);if(this.u.L())return o;var b=this;return this.u.z(function(c,d){return a(new S(d,b.gc.F(c)))})};S.prototype.forEach=S.prototype.forEach;S.prototype.mb=function(){A("Firebase.DataSnapshot.hasChildren",0,0,arguments.length);return this.u.L()?o:!this.u.f()};S.prototype.hasChildren=S.prototype.mb;
S.prototype.name=function(){A("Firebase.DataSnapshot.name",0,0,arguments.length);return this.gc.name()};S.prototype.name=S.prototype.name;S.prototype.Tb=function(){A("Firebase.DataSnapshot.numChildren",0,0,arguments.length);return this.u.Tb()};S.prototype.numChildren=S.prototype.Tb;S.prototype.Gd=function(){A("Firebase.DataSnapshot.ref",0,0,arguments.length);return this.gc};S.prototype.ref=S.prototype.Gd;function ec(a){this.zc=a;this.bc=[];this.Ta=0;this.qc=-1;this.Ka=m}function fc(a,b,c){for(a.bc[b]=c;a.bc[a.Ta];){b=a.bc[a.Ta];delete a.bc[a.Ta];for(c=0;c<b.length;++c)b[c]&&a.zc(b[c]);if(a.Ta===a.qc){a.Ka&&(clearTimeout(a.Ka),a.Ka(),a.Ka=m);break}a.Ta++}};function gc(a,b){for(var c in a)b.call(j,a[c],c,a)}function hc(a){var b={},c;for(c in a)b[c]=a[c];return b};function ic(){this.hb={}}function jc(a,b,c){t(c)||(c=1);D(a.hb,b)||(a.hb[b]=0);a.hb[b]+=c}ic.prototype.get=function(){return hc(this.hb)};function kc(a){this.rd=a;this.Qb=m}kc.prototype.get=function(){var a=this.rd.get(),b=hc(a);if(this.Qb)for(var c in this.Qb)b[c]-=this.Qb[c];this.Qb=a;return b};function lc(a,b){this.Hc={};this.jc=new kc(a);this.o=b;setTimeout(v(this.bd,this),10+6E4*Math.random())}lc.prototype.bd=function(){var a=this.jc.get(),b={},c=o,d;for(d in a)0<a[d]&&D(this.Hc,d)&&(b[d]=a[d],c=k);c&&(a=this.o,a.X&&(b={c:b},a.e("reportStats",b),a.Ca("s",b)));setTimeout(v(this.bd,this),6E5*Math.random())};var mc={},nc={};function oc(a){a=a.toString();mc[a]||(mc[a]=new ic);return mc[a]};var pc=require("http");function qc(a,b,c){this.Ob=a;this.e=Qb(a);this.H=b;this.V=oc(b);this.Oa=c;this.ba=this.Ia=o;this.ca=new rc;this.buffer={};this.da=[];this.Fd=function(a){b.host!==b.T&&(a.ns=b.Ya);var c=[],g;for(g in a)a.hasOwnProperty(g)&&c.push(g+"="+a[g]);return"/.hp?"+c.join("&")}}qc.isAvailable=q(o);r=qc.prototype;
r.open=function(a,b){this.ib=0;this.G=b;this.Ed=new ec(a);var c=this;this.P=setTimeout(function(){c.e("Timed out trying to connect.");c.close();c.P=m},3E4);var d=Math.floor(1E8*Math.random()),e={start:"t"};e.ser=d;e.v="5";this.Oa&&(e.s=this.Oa);this.e("Connecting via httppoll to "+this.H.T);sc(this,d,e)};r.start=function(){this.fb=k;for(this.jb=Math.floor(1E8*Math.random());this.za(););};
r.send=function(a){for(var a=y(a),a=Jb(a),a=Xb(a,1048576),b=0;b<a.length;++b)this.da.push({Cc:this.ib,Lc:a.length,kb:a[b]}),this.fb&&this.za(),this.ib++};r.close=function(){if(!this.ba){this.e("Httppoll is being closed");if(this.fb&&this.id&&this.xb){this.e("doing a disconnect");var a={};a.id=this.id;a.pw=this.xb;a.disconn="t";sc(this,0,a)}this.Ea()}};
r.za=function(){if(this.fb&&this.ca.count()<(0<this.da.length?2:1)){var a=this.jb++,b={};b.id=this.id;b.pw=this.xb;b.ser=a;for(var c=[];0<this.da.length;)if(1048608>=this.da[0].kb.length){var d=this.da.shift();c.push(d.Cc+":"+d.Lc+":"+d.kb)}else break;var e=this,d=setTimeout(function(){e.ca.remove(a);e.za()},25E3);this.ca.add(a,d);sc(this,a,b,c.join("\n"));return k}return o};r.ia=function(){this.ba||(this.e("Httppoll is closing itself"),this.Ea(),this.G&&(this.G(this.Ia),this.G=m))};
r.Ea=function(){this.ba=k;this.fb=o;this.P&&(clearTimeout(this.P),this.P=m);tc(this.ca,function(a){clearTimeout(a)});this.ca.clear()};
function sc(a,b,c,d){var d=d||"",c=a.Fd(c),e=a.H.T,g=e.split(":"),h=a.H.Eb?443:80;1<g.length&&(e=g[0],h=parseInt(g[1]));c=pc.request({method:"POST",host:e,port:h,path:c},function(c){if(a.P){clearTimeout(a.P);a.P=m}var d=a.ca.get(b);d&&clearTimeout(d);a.ca.remove(b);a.za();if(c.statusCode!=200){a.e("error code received: "+c.statusCode);a.ia()}else{if("x-firebase-poll-id"in c.headers&&"x-firebase-poll-pw"in c.headers){a.id=c.headers["x-firebase-poll-id"];a.xb=c.headers["x-firebase-poll-pw"]}if("x-firebase-poll-close"in
c.headers){a.e("recvd close");a.fb=o}c.on("data",function(b){b=b.toString();a.buffer[c]=c in a.buffer?a.buffer[c]+b:b});c.on("end",function(){if(c in a.buffer){var b=a.buffer[c];delete a.buffer[c];var b=qa(b),d=parseInt(Vb("x-firebase-response",c.headers));fc(a.Ed,d,b)}})}});c.on("error",function(b){a.e("An error occurred: "+b.message);a.ia()});c.end(d)};var uc=m,uc=require("faye-websocket").Client;function vc(a,b,c){this.Ob=a;this.e=Qb(this.Ob);this.frames=this.pb=m;this.Ic=0;this.V=oc(b);this.Sa=(b.Eb?"wss://":"ws://")+b.T+"/.ws?v=5";b.host!==b.T&&(this.Sa=this.Sa+"&ns="+b.Ya);c&&(this.Sa=this.Sa+"&s="+c)}var wc;
vc.prototype.open=function(a,b){this.ja=b;this.Yb=a;this.e("websocket connecting to "+this.Sa);this.Z=new uc(this.Sa);this.Ia=o;var c=this;this.Z.onopen=function(){c.e("Websocket connected.");c.Ia=k};this.Z.onclose=function(){c.e("Websocket connection was disconnected.");c.Z=m;c.ia()};this.Z.onmessage=function(a){if(c.Z!==m)if(a=a.data,jc(c.V,"bytes_received",a.length),xc(c),c.frames!==m)yc(c,a);else{a:{z(c.frames===m,"We already have a frame buffer");if(4>=a.length){var b=Number(a);if(!isNaN(b)){c.Ic=
b;c.frames=[];a=m;break a}}c.Ic=1;c.frames=[]}a!==m&&yc(c,a)}};this.Z.onerror=function(){c.e("WebSocket error.  Closing connection.");c.ia()}};vc.prototype.start=function(){};vc.isAvailable=function(){return!("undefined"!==typeof navigator&&"Opera"===navigator.appName)&&uc!==m&&!wc};function yc(a,b){a.frames.push(b);if(a.frames.length==a.Ic){var c=a.frames.join("");a.frames=m;c=qa(c);a.Yb(c)}}
vc.prototype.send=function(a){xc(this);a=y(a);jc(this.V,"bytes_sent",a.length);a=Xb(a,16384);1<a.length&&this.Z.send(String(a.length));for(var b=0;b<a.length;b++)this.Z.send(a[b])};vc.prototype.Ea=function(){this.ba=k;this.pb&&(clearTimeout(this.pb),this.pb=m);this.Z&&(this.Z.close(),this.Z=m)};vc.prototype.ia=function(){this.ba||(this.e("WebSocket is closing itself"),this.Ea(),this.ja&&(this.ja(this.Ia),this.ja=m))};vc.prototype.close=function(){this.ba||(this.e("WebSocket is being closed"),this.Ea())};
function xc(a){clearTimeout(a.pb);a.pb=setInterval(function(){a.Z.send("0");xc(a)},45E3)};function rc(){this.set={}}r=rc.prototype;r.add=function(a,b){this.set[a]=b!==m?b:k};r.contains=function(a){return D(this.set,a)};r.get=function(a){return this.contains(a)?this.set[a]:j};r.remove=function(a){delete this.set[a]};r.clear=function(){this.set={}};r.f=function(){var a;a:{for(a in this.set){a=o;break a}a=k}return a};r.count=function(){var a=0,b;for(b in this.set)a++;return a};function tc(a,b){for(var c in a.set)D(a.set,c)&&b(c,a.set[c])}
r.keys=function(){var a=[],b;for(b in this.set)D(this.set,b)&&a.push(b);return a};function zc(a,b,c){this.Ob=a;this.e=Qb(a);this.Rd=b;this.V=oc(b);this.Oa=c;this.Ia=o;this.Kb=function(a){b.host!==b.T&&(a.ns=b.Ya);var c=[],g;for(g in a)a.hasOwnProperty(g)&&c.push(g+"="+a[g]);return(b.Eb?"https://":"http://")+b.T+"/.lp?"+c.join("&")}}var Ac,Bc;
zc.prototype.open=function(a,b){this.ib=0;this.G=b;this.Yc=new ec(a);this.ba=o;var c=this;this.P=setTimeout(function(){c.e("Timed out trying to connect.");c.ia();c.P=m},3E4);if(!c.ba){c.ka=new Cc(function(a,b,d,i,l){jc(c.V,"bytes_received",y(arguments).length);if(c.ka)if(c.P&&(clearTimeout(c.P),c.P=m),c.Ia=k,"start"==a)c.id=b,c.xb=d;else if("close"===a)if(b){c.ka.gd=o;var n=c.Yc;n.qc=b;n.Ka=function(){c.ia()};n.qc<n.Ta&&(n.Ka(),n.Ka=m)}else c.ia();else f(Error("Unrecognized command received: "+a))},
function(a,b){jc(c.V,"bytes_received",y(arguments).length);fc(c.Yc,a,b)},function(){c.ia()},c.Kb);var d={start:"t"};d.ser=Math.floor(1E8*Math.random());c.ka.Od&&(d.cb=c.ka.Od);d.v="5";c.Oa&&(d.s=c.Oa);d=c.Kb(d);c.e("Connecting via long-poll to "+d);Dc(c.ka,d,function(){})}};zc.prototype.start=function(){var a=this.ka,b=this.xb;a.uc=this.id;a.Xc=b;for(a.nc=k;a.za(););};
zc.isAvailable=function(){return!Bc&&!("object"===typeof window&&window.chrome&&window.chrome.extension&&!/^chrome/.test(window.location.href))&&(Ac||o)};zc.prototype.Ea=function(){this.ba=k;this.ka&&(this.ka.close(),this.ka=m);this.Wc&&(document.body.removeChild(this.Wc),this.Wc=m);this.P&&(clearTimeout(this.P),this.P=m)};zc.prototype.ia=function(){this.ba||(this.e("Longpoll is closing itself"),this.Ea(),this.G&&(this.G(this.Ia),this.G=m))};
zc.prototype.close=function(){this.ba||(this.e("Longpoll is being closed."),this.Ea())};zc.prototype.send=function(a){a=y(a);jc(this.V,"bytes_sent",a.length);for(var a=Jb(a),a=Xb(a,1840),b=0;b<a.length;b++){var c=this.ka;c.da.push({Cc:this.ib,Lc:a.length,kb:a[b]});c.nc&&c.za();this.ib++}};function Cc(a,b,c,d){this.Kb=d;this.ja=c;this.ca=new rc;this.da=[];this.jb=Math.floor(1E8*Math.random());this.gd=k;this.sd=a;this.Cd=b}
Cc.prototype.close=function(){this.nc=o;if(this.Rb){this.Rb.Pd.body.innerHTML="";var a=this;setTimeout(function(){a.Rb!==m&&(document.body.removeChild(a.Rb),a.Rb=m)},0)}if(this.uc){var b={disconn:"t"};b.id=this.uc;b.pw=this.Xc;b=this.Kb(b);Ec(b)}if(b=this.ja)this.ja=m,b()};
Cc.prototype.za=function(){if(this.nc&&this.gd&&this.ca.count()<(0<this.da.length?2:1)){this.jb++;var a={};a.id=this.uc;a.pw=this.Xc;a.ser=this.jb;for(var a=this.Kb(a),b="",c=0;0<this.da.length;)if(1870>=this.da[0].kb.length+30+b.length){var d=this.da.shift(),b=b+"&seg"+c+"="+d.Cc+"&ts"+c+"="+d.Lc+"&d"+c+"="+d.kb;c++}else break;var a=a+b,e=this.jb,g=this;g.ca.add(e);var h=function(){g.ca.remove(e);g.za()},i=setTimeout(h,25E3);Dc(this,a,function(){clearTimeout(i);h()});return k}return o};
function Ec(a,b){Fc||(Fc=require("request"));Fc(a,function(a,d,e){a&&f("Rest request for "+url+" failed.");b&&b(e)})}var Fc;function Dc(a,b,c){Ec({url:b,Qd:k},function(b){Gc(a,b);c()})}function Gc(a,b){eval("var document = function(pLPCommand, pRTLPCB) {"+b+"}");document(a.sd,a.Cd)};function Hc(){function a(a,c){c&&c.isAvailable()&&b.push(c)}var b=[],c=Ic;if("array"==da(c))for(var d=0;d<c.length;++d)a(0,c[d]);else gc(c,a);this.kc=b}var Ic=[zc,qc,vc];function Jc(a,b,c,d,e,g){this.id=a;this.e=Qb("c:"+this.id+":");this.zc=c;this.ub=d;this.G=e;this.yc=g;this.H=b;this.ac=[];this.Mc=0;this.Kc=new Hc;this.sa=0;this.e("Connection created");Kc(this)}function Kc(a){var b;var c=a.Kc;0<c.kc.length?b=c.kc[0]:f(Error("No transports available"));a.K=new b("c:"+a.id+":"+a.Mc++,a.H);var d=Lc(a,a.K),e=Mc(a,a.K);a.Hb=a.K;a.Db=a.K;a.A=m;setTimeout(function(){a.K&&a.K.open(d,e)},0)}
function Mc(a,b){return function(c){b===a.K?(a.K=m,!c&&0===a.sa?(a.e("Realtime connection failed."),"s-"===a.H.T.substr(0,2)&&(O.removeItem(a.H.Ya),a.H.T=a.H.host)):1===a.sa&&a.e("Realtime connection lost."),a.close()):b===a.A?(c=a.A,a.A=m,(a.Hb===c||a.Db===c)&&a.close()):a.e("closing an old connection")}}
function Lc(a,b){return function(c){if(2!=a.sa)if(b===a.Db){var d=Vb("t",c),c=Vb("d",c);if("c"==d){if(d=Vb("t",c),"d"in c)if(c=c.d,"h"===d){var d=c.ts,e=c.v,g=c.h;a.Oa=c.s;rb(a.H,g);if(0==a.sa&&(a.K.start(),c=a.K,a.e("Realtime connection established."),a.K=c,a.sa=1,a.ub&&(a.ub(d),a.ub=m),"5"!==e&&Tb("Protocol version mismatch detected"),c=1<a.Kc.kc.length?a.Kc.kc[1]:m))a.A=new c("c:"+a.id+":"+a.Mc++,a.H,a.Oa),a.A.open(Lc(a,a.A),Mc(a,a.A))}else if("n"===d){a.e("recvd end transmission on primary");
a.Db=a.A;for(c=0;c<a.ac.length;++c)a.Wb(a.ac[c]);a.ac=[];Nc(a)}else"s"===d?(a.e("Connection shutdown command received. Shutting down..."),a.yc&&(a.yc(c),a.yc=m),a.G=m,a.close()):"r"===d?(a.e("Reset packet received.  New host: "+c),rb(a.H,c),1===a.sa?a.close():(Oc(a),Kc(a))):Rb("Unknown control packet command: "+d)}else"d"==d&&a.Wb(c)}else b===a.A?(d=Vb("t",c),c=Vb("d",c),"c"==d?"t"in c&&(c=c.t,"a"===c?(a.A.start(),a.e("sending client ack on secondary"),a.A.send({t:"c",d:{t:"a",d:{}}}),a.e("Ending transmission on primary"),
a.K.send({t:"c",d:{t:"n",d:{}}}),a.Hb=a.A,Nc(a)):"r"===c&&(a.e("Got a reset on secondary, closing it"),a.A.close(),(a.Hb===a.A||a.Db===a.A)&&a.close())):"d"==d?a.ac.push(c):f(Error("Unknown protocol layer: "+d))):a.e("message on old connection")}}Jc.prototype.Dc=function(a){a={t:"d",d:a};1!==this.sa&&f("Connection is not connected");this.Hb.send(a)};function Nc(a){a.Hb===a.A&&a.Db===a.A&&(a.e("cleaning up and promoting a connection: "+a.A.Ob),a.K=a.A,a.A=m)}Jc.prototype.Wb=function(a){this.zc(a)};
Jc.prototype.close=function(){2!==this.sa&&(this.e("Closing realtime connection."),this.sa=2,Oc(this),this.G&&(this.G(),this.G=m))};function Oc(a){a.e("Shutting down all connections");a.K&&(a.K.close(),a.K=m);a.A&&(a.A.close(),a.A=m)};function Pc(a,b,c,d){this.id=Qc++;this.e=Qb("p:"+this.id+":");this.Fb=k;this.ha={};this.U=[];this.vb=0;this.tb=[];this.X=o;this.fc=1E3;this.Xb=b||ca;this.Vb=c||ca;this.sb=d||ca;this.H=a;this.Bc=m;this.cc=[];this.Ba={};this.Jd=0;this.qb=this.Vc=m;setTimeout(v(this.Nc,this),0)}var Qc=0,Rc=0;r=Pc.prototype;
r.Ca=function(a,b,c,d){var e=++this.Jd,a={r:e,a:a,b:b};this.e(y(a));this.X?this.Ab.Dc(a):this.cc.push(a);var g=this,a=setTimeout(function(){var a=g.Ba[e];a&&(delete g.Ba[e],a.na&&a.na.Zb&&a.na.Zb())},45E3);this.Ba[e]={na:{Yb:c,Zb:d},kd:a}};function Sc(a,b,c,d,e){a.e("Listen on "+b+" for "+c);var g={p:b},d=kb(d,function(a){return Ja(a)});"{}"!==c&&(g.q=d);a.Ca("l",g,function(d){a.e("listen response",d);d=d.s;"ok"!==d&&Tc(a,b,c);e&&e(d)},function(){a.e("timed out on listen...")})}
r.gb=function(a,b,c){this.Ga={td:a,Pc:o,la:b,Mb:c};this.e("Authenticating using credential: "+this.Ga);Uc(this)};r.Ib=function(){delete this.Ga;this.sb(o);this.X&&this.Ca("unauth",{},function(){},function(){})};function Uc(a){var b=a.Ga;a.X&&b&&a.Ca("auth",{cred:b.td},function(c){var d=c.s,c=c.d||"error";"ok"!==d&&a.Ga===b&&delete a.Ga;b.Pc?"ok"!==d&&b.Mb&&b.Mb(d,c):(b.Pc=k,b.la&&b.la(d,c));a.sb("ok"===d)},function(){a.e("timed out on auth...")})}
r.md=function(a,b,c){a=a.toString();if(Tc(this,a,b)&&this.X){this.e("Unlisten on "+a+" for "+b);var d=this,a={p:a},c=kb(c,function(a){return Ja(a)});"{}"!==b&&(a.q=c);this.Ca("u",a,m,function(){d.e("timed out on unlisten...")})}};function Vc(a,b,c,d){a.X?Wc(a,"o",b,c,d):a.tb.push({Ac:b,action:"o",data:c,C:d})}r.xc=function(a,b){this.X?Wc(this,"oc",a,m,b):this.tb.push({Ac:a,action:"oc",data:m,C:b})};
function Wc(a,b,c,d,e){c={p:c,d:d};a.e("onDisconnect "+b,c);a.Ca(b,c,function(a){e&&setTimeout(function(){e(a.s)},0)},function(){a.e("timed out on onDisconnect...")})}r.put=function(a,b,c,d){Xc(this,"p",a,b,c,d)};function Xc(a,b,c,d,e,g){c={p:c,d:d};t(g)&&(c.h=g);a.U.push({action:b,cd:c,C:e});a.vb++;b=a.U.length-1;a.X&&Yc(a,b)}
function Yc(a,b){var c=a.U[b].action,d=a.U[b].C;a.Ca(c,a.U[b].cd,function(e){a.e(c+" response",e);delete a.U[b];a.vb--;0===a.vb&&(a.U=[]);d&&d(e.s)},function(){a.e("timed out on put...")})}
r.Wb=function(a){if("r"in a){this.e("from server: "+y(a));var b=a.r,c=this.Ba[b];c&&(delete this.Ba[b],clearTimeout(c.kd),c.na&&c.na.Yb&&c.na.Yb(a.b))}else"error"in a&&f("A server-side error has occurred: "+a.error),"a"in a&&(b=a.a,a=a.b,this.e("handleServerMessage",b,a),"d"===b?this.Xb(a.p,a.d):"m"===b?this.Xb(a.p,a.d,k):"c"===b?(b=a.p,a=(a=a.q)?kb(a,function(a){return Ka(a)}).join("$"):"{}",(a=Tc(this,b,a))&&a.C&&a.C("permission_denied")):"ac"===b?(b=a.s,a=a.d,c=this.Ga,delete this.Ga,c&&c.Mb&&
c.Mb(b,a),this.sb(o)):"sd"===b?this.Bc?this.Bc(a):"msg"in a&&"undefined"!==typeof console&&console.log("FIREBASE: "+a.msg.replace("\n","\nFIREBASE: ")):Rb("Unrecognized action received from server: "+y(b)+"\nAre you using the latest client?"))};
r.ub=function(a){this.e("connection ready");this.X=k;this.qb=(new Date).getTime();Wb=a-(new Date).getTime();for(a=0;a<this.cc.length;a++)this.Ab.Dc(this.cc[a]);this.cc=[];Uc(this);for(a=0;a<this.U.length;a++)this.U[a]&&Yc(this,a);for(var b in this.ha)for(var c in this.ha[b])a=this.ha[b][c],Sc(this,b,c,a.$a,a.C);for(;this.tb.length;)b=this.tb.shift(),Wc(this,b.action,b.Ac,b.data,b.C);this.Vb(k)};
r.$c=function(){this.X=o;this.e("data client disconnected");var a=v(function(){this.Nc()},this);if(this.Fb){this.qb&&(3E4<(new Date).getTime()-this.qb&&(this.fc=1E3),this.qb=m);var b=Math.max(0,this.fc-((new Date).getTime()-this.Vc)),b=Math.random()*b;this.e("Trying to reconnect in "+b+"ms");setTimeout(a,b);this.fc=Math.min(3E5,1.5*this.fc)}else{for(var c=0;c<this.U.length;c++){var d=this.U[c];d&&"h"in d.cd&&(d.C&&d.C("disconnect"),delete this.U[c],this.vb--)}0===this.vb&&(this.U=[]);for(b in this.Ba)c=
this.Ba[b],delete this.Ba[b],c!==m&&(c.na&&c.na.Zb&&c.na.Zb(),clearTimeout(c.kd));this.ed=function(){setTimeout(a,0)}}this.Vb(o)};r.Nc=function(){if(this.Fb){this.e("Making a connection attempt");this.Vc=(new Date).getTime();this.qb=m;var a=v(this.Wb,this),b=v(this.ub,this),c=v(this.$c,this),d=this.id+":"+Rc++,e=this;this.Ab=new Jc(d,this.H,a,b,c,function(a){e.Fb=o;f(Error(a))})}};r.Wa=function(){this.Fb=o;this.Ab?this.Ab.close():this.$c()};r.Cb=function(){this.Fb=k;this.ed();this.ed=j};
function Tc(a,b,c){b=(new I(b)).toString();c||(c="{}");var d=a.ha[b][c];delete a.ha[b][c];return d};function Zc(){this.n=this.D=m}function $c(a,b,c){if(b.f())a.D=c,a.n=m;else if(a.D!==m)a.D=a.D.Fa(b,c);else{a.n==m&&(a.n=new rc);var d=F(b);a.n.contains(d)||a.n.add(d,new Zc);a=a.n.get(d);b=J(b);$c(a,b,c)}}function ad(a,b){if(b.f())return a.D=m,a.n=m,k;if(a.D!==m){if(a.D.L())return o;var c=a.D;a.D=m;c.z(function(b,c){$c(a,new I(b),c)});return ad(a,b)}return a.n!==m?(c=F(b),b=J(b),a.n.contains(c)&&ad(a.n.get(c),b)&&a.n.remove(c),a.n.f()?(a.n=m,k):o):k}
function bd(a,b,c){a.D!==m?c(b,a.D):a.z(function(a,e){var g=new I(b.toString()+"/"+a);bd(e,g,c)})}Zc.prototype.z=function(a){this.n!==m&&tc(this.n,function(b,c){a(b,c)})};function cd(){this.Na=P}function T(a,b){return a.Na.J(b)}function U(a,b,c){a.Na=a.Na.Fa(b,c)}cd.prototype.toString=function(){return this.Na.toString()};function dd(){this.Da=new cd;this.N=new cd;this.Pa=new cd;this.yb=new Oa}function ed(a,b){for(var c=T(a.Da,b),d=T(a.N,b),e=L(a.yb,b),g=o,h=e;h!==m;){if(h.j()!==m){g=k;break}h=h.parent()}if(g)return o;c=fd(c,d,e);return c!==d?(U(a.N,b,c),k):o}function fd(a,b,c){if(c.f())return a;if(c.j()!==m)return b;a=a||P;c.z(function(d){var d=d.name(),e=a.S(d),g=b.S(d),h=L(c,d),e=fd(e,g,h);a=a.I(d,e)});return a}
dd.prototype.set=function(a,b){var c=this,d=[];jb(b,function(a){var b=a.path,a=a.Ja,h=Hb();M(L(c.yb,b),h);U(c.N,b,a);d.push({path:b,Kd:h})});return d};function gd(a,b){jb(b,function(b){var d=b.Kd,b=L(a.yb,b.path),e=b.j();z(e!==m,"pendingPut should not be null.");e===d&&M(b,m)})};function hd(){this.Ha=[]}function id(a,b){if(0!==b.length){a.Ha.push.apply(a.Ha,b);for(var c=0;c<a.Ha.length;c++)if(a.Ha[c]){var d=a.Ha[c];a.Ha[c]=m;var e=d.la;e(d.hd,d.zb)}a.Ha=[]}};function V(a,b,c,d){this.type=a;this.pa=b;this.$=c;this.zb=d};function jd(a){this.O=a;this.ma=[];this.Oc=new hd}function kd(a,b,c,d,e){a.ma.push({type:b,la:c,cancel:d,aa:e});var d=[],g=ld(a.g);a.ob&&g.push(new V("value",a.g));for(var h=0;h<g.length;h++)if(g[h].type===b){var i=new W(a.O.w,a.O.path);g[h].$&&(i=i.F(g[h].$));d.push({la:e?v(c,e):c,hd:new S(g[h].pa,i),zb:g[h].zb})}id(a.Oc,d)}jd.prototype.dc=function(a,b){b=this.ec(a,b);b!=m&&md(this,b)};
function md(a,b){for(var c=[],d=0;d<b.length;d++){var e=b[d],g=e.type,h=new W(a.O.w,a.O.path);b[d].$&&(h=h.F(b[d].$));h=new S(b[d].pa,h);"value"===e.type&&!h.mb()?g+="("+h.W()+")":"value"!==e.type&&(g+=" "+h.name());Ob(a.O.w.o.id+": event:"+a.O.path+":"+a.O.La()+":"+g);for(g=0;g<a.ma.length;g++){var i=a.ma[g];b[d].type===i.type&&c.push({la:i.aa?v(i.la,i.aa):i.la,hd:h,zb:e.zb})}}id(a.Oc,c)}
function ld(a){var b=[];if(!a.L()){var c=m;a.z(function(a,e){b.push(new V("child_added",e,a,c));c=a})}return b}function nd(a){a.ob||(a.ob=k,md(a,[new V("value",a.g)]))};function od(a,b){jd.call(this,a);this.g=b}ja(od,jd);od.prototype.ec=function(a,b){this.g=a;this.ob&&b!=m&&b.push(new V("value",this.g));return b};od.prototype.lb=function(){return{}};function rd(a,b){this.Pb=a;this.wc=b}
function sd(a,b,c,d,e){var g=a.J(c),h=b.J(c),d=new rd(d,e),e=td(d,c,g,h),i=o;if(!g.f()&&!h.f()&&g.k()!==h.k())var i=a.J(c.parent()),l=b.J(c.parent()),n=La(c),i=i.Y(n,g)!=l.Y(n,h);if(e||i){g=c;c=e;for(h=i;g.parent()!==m;){var p=a.J(g),e=b.J(g),i=g.parent();if(!d.Pb||L(d.Pb,i).j())l=b.J(i),n=[],g=La(g),p.f()?(p=l.Y(g,e),n.push(new V("child_added",e,g,p))):e.f()?n.push(new V("child_removed",p,g)):(p=l.Y(g,e),h&&n.push(new V("child_moved",e,g,p)),c&&n.push(new V("child_changed",e,g,p))),d.wc(i,l,n);h&&
(h=o,c=k);g=i}}}function td(a,b,c,d){var e,g=[];c===d?e=o:c.L()&&d.L()?e=c.j()!==d.j():c.L()?(ud(a,b,P,d,g),e=k):d.L()?(ud(a,b,c,P,g),e=k):e=ud(a,b,c,d,g);e?a.wc(b,d,g):c.k()!==d.k()&&a.wc(b,d,m);return e}
function ud(a,b,c,d,e){var g=o,h=!a.Pb||!L(a.Pb,b).f(),i=[],l=[],n=[],p=[],s={},w={},x,N,K,H;x=c.Va();K=Za(x);N=d.Va();for(H=Za(N);K!==m||H!==m;){c=K===m?1:H===m?-1:K.key===H.key?0:dc({name:K.key,Aa:K.value.k()},{name:H.key,Aa:H.value.k()});if(0>c)g=ua(s,K.key),t(g)?(n.push({Qc:K,ld:i[g]}),i[g]=m):(w[K.key]=l.length,l.push(K)),g=k,K=Za(x);else{if(0<c)g=ua(w,H.key),t(g)?(n.push({Qc:l[g],ld:H}),l[g]=m):(s[H.key]=i.length,i.push(H)),g=k;else{c=b.F(H.key);if(c=td(a,c,K.value,H.value))p.push(H),g=k;K=
Za(x)}H=Za(N)}if(!h&&g)return k}for(h=0;h<l.length;h++)if(s=l[h])c=b.F(s.key),td(a,c,s.value,P),e.push(new V("child_removed",s.value,s.key));for(h=0;h<i.length;h++)if(s=i[h])c=b.F(s.key),l=d.Y(s.key,s.value),td(a,c,P,s.value),e.push(new V("child_added",s.value,s.key,l));for(h=0;h<n.length;h++)s=n[h].Qc,i=n[h].ld,c=b.F(i.key),l=d.Y(i.key,i.value),e.push(new V("child_moved",i.value,i.key,l)),(c=td(a,c,s.value,i.value))&&p.push(i);for(h=0;h<p.length;h++)a=p[h],l=d.Y(a.key,a.value),e.push(new V("child_changed",
a.value,a.key,l));return g};function vd(){this.Q=this.ta=m;this.set={}}ja(vd,rc);r=vd.prototype;r.setActive=function(a){this.ta=a};function wd(a){return a.contains("default")}function xd(a){return a.ta!=m&&wd(a)}r.defaultView=function(){return wd(this)?this.get("default"):m};r.path=aa("Q");r.toString=function(){return kb(this.keys(),function(a){return"default"===a?"{}":a}).join("$")};r.$a=function(){var a=[];tc(this,function(b,c){a.push(c.O)});return a};function yd(a,b){jd.call(this,a);this.g=P;this.ec(b,ld(b))}ja(yd,jd);
yd.prototype.ec=function(a,b){if(b===m)return b;var c=[],d=this.O;t(d.ga)&&(t(d.ra)&&d.ra!=m?c.push(function(a,b){var c=Ub(b,d.ga);return 0<c||0===c&&a>=d.ra}):c.push(function(a,b){return 0<=Ub(b,d.ga)}));t(d.va)&&(t(d.Ua)?c.push(function(a,b){var c=Ub(b,d.va);return 0>c||0===c&&a<=d.Ua}):c.push(function(a,b){return 0>=Ub(b,d.va)}));var e=m,g=m;if(t(this.O.xa))if(t(this.O.ga)){if(e=zd(a,c,this.O.xa,o)){var h=a.S(e).k();c.push(function(a,b){var c=Ub(b,h);return 0>c||0===c&&a<=e})}}else if(g=zd(a,c,
this.O.xa,k)){var i=a.S(g).k();c.push(function(a,b){var c=Ub(b,i);return 0<c||0===c&&a>=g})}for(var l=[],n=[],p=[],s=[],w=0;w<b.length;w++){var x=b[w].$,N=b[w].pa;switch(b[w].type){case "child_added":Ad(c,x,N)&&(this.g=this.g.I(x,N),n.push(b[w]));break;case "child_removed":this.g.S(x).f()||(this.g=this.g.I(x,m),l.push(b[w]));break;case "child_changed":!this.g.S(x).f()&&Ad(c,x,N)&&(this.g=this.g.I(x,N),s.push(b[w]));break;case "child_moved":var K=!this.g.S(x).f(),H=Ad(c,x,N);K?H?(this.g=this.g.I(x,
N),p.push(b[w])):(l.push(new V("child_removed",this.g.S(x),x)),this.g=this.g.I(x,m)):H&&(this.g=this.g.I(x,N),n.push(b[w]))}}var pd=e||g;if(pd){var qd=(w=g!==m)?this.g.Rc():this.g.Sc(),$b=o,Sa=o,Ta=this;(w?a.rc:a.z).call(a,function(a,b){!Sa&&qd===m&&(Sa=k);if(Sa&&$b)return k;$b?(l.push(new V("child_removed",Ta.g.S(a),a)),Ta.g=Ta.g.I(a,m)):Sa&&(n.push(new V("child_added",b,a)),Ta.g=Ta.g.I(a,b));qd===a&&(Sa=k);a===pd&&($b=k)})}for(w=0;w<n.length;w++)c=n[w],x=this.g.Y(c.$,c.pa),l.push(new V("child_added",
c.pa,c.$,x));for(w=0;w<p.length;w++)c=p[w],x=this.g.Y(c.$,c.pa),l.push(new V("child_moved",c.pa,c.$,x));for(w=0;w<s.length;w++)c=s[w],x=this.g.Y(c.$,c.pa),l.push(new V("child_changed",c.pa,c.$,x));this.ob&&0<l.length&&l.push(new V("value",this.g));return l};function zd(a,b,c,d){if(a.L())return m;var e=m;(d?a.rc:a.z).call(a,function(a,d){if(Ad(b,a,d)&&(e=a,c--,0===c))return k});return e}function Ad(a,b,c){for(var d=0;d<a.length;d++)if(!a[d](b,c.k()))return o;return k}
yd.prototype.sc=function(a){return this.g.S(a)!==P};yd.prototype.lb=function(a,b,c){var d={};this.g.L()||this.g.z(function(a){d[a]=k});var e=this.g,c=T(c,new I("")),g=new Oa;M(L(g,this.O.path),k);var h=P.Fa(a,b),i=[];sd(c,h,a,g,function(a,b,c){c!==m&&(i=i.concat(c))});this.ec(b,i);this.g.L()||this.g.z(function(a){d[a]=k});this.g=e;return d};function Bd(a,b){this.o=a;this.i=b;this.Zc=b.Na;this.ua=new Oa}
Bd.prototype.Lb=function(a,b,c,d,e){var g=a.path,h=L(this.ua,g),i=h.j();i===m?(i=new vd,M(h,i)):z(!i.f(),"We shouldn't be storing empty QueryMaps");var l=a.La();if(i.contains(l))kd(i.get(l),b,c,d,e);else{var n=this.i.Na.J(g),a="default"===a.La()?new od(a,n):new yd(a,n);if(xd(i)||Cd(h))i.add(l,a),i.Q||(i.Q=a.O.path);else{var p,s;i.f()||(p=i.toString(),s=i.$a());i.add(l,a);i.Q||(i.Q=a.O.path);i.setActive(Dd(this,i));p&&s&&this.o.md(i.path(),p,s)}xd(i)&&Qa(h,function(a){if(a=a.j()){a.ta&&a.ta();a.ta=
m}});kd(a,b,c,d,e);(b=(b=Ra(L(this.ua,g),function(a){var b;if(b=a.j())if(b=a.j().defaultView())b=a.j().defaultView().ob;if(b)return k},k))||this.o===m)&&nd(a)}};function Ed(a,b,c,d,e){for(var g=a.get(b),h=o,i=g.ma.length-1;0<=i;i--){var l=g.ma[i];if((!c||l.type===c)&&(!d||l.la===d)&&(!e||l.aa===e))if(g.ma.splice(i,1),h=k,c&&d)break}(c=h&&!(0<g.ma.length))&&a.remove(b);return c}Bd.prototype.hc=function(a,b,c,d){var e=L(this.ua,a.path).j();return e===m?m:Fd(this,e,a,b,c,d)};
function Fd(a,b,c,d,e,g){var h=b.path(),h=L(a.ua,h),c=c?c.La():m,i=[];c&&"default"!==c?Ed(b,c,d,e,g)&&i.push(c):jb(b.keys(),function(a){Ed(b,a,d,e,g)&&i.push(a)});b.f()&&M(h,m);c=Cd(h);if(0<i.length&&!c){for(var l=h,n=h.parent(),c=o;!c&&n;){var p=n.j();if(p){z(!xd(p));var s=l.name(),w=o;tc(p,function(a,b){w=b.sc(s)||w});w&&(c=k)}l=n;n=n.parent()}l=m;if(!xd(b)){n=b.ta;b.ta=m;var x=[],N=function(b){var c=b.j();c&&wd(c)?(x.push(c.path()),c.ta==m&&c.setActive(Dd(a,c))):(c&&c.ta==m&&c.setActive(Dd(a,c)),
b.z(N))};N(h);l=x;n&&n()}return c?m:l}return m}function Gd(a,b,c){Qa(L(a.ua,b),function(a){(a=a.j())&&tc(a,function(a,b){nd(b)})},c,k)}function Hd(a,b,c){function d(a){for(var b=0;b<c.length;++b)if(c[b].contains(a))return k;return o}var e=a.Zc,g=a.i.Na;a.Zc=g;sd(e,g,b,a.ua,function(c,e,g){if(b.contains(c)){var n=d(c);n&&Gd(a,c,o);a.dc(c,e,g);n&&Gd(a,c,k)}else a.dc(c,e,g)});d(b)&&Gd(a,b,k)}Bd.prototype.dc=function(a,b,c){a=L(this.ua,a).j();a!==m&&tc(a,function(a,e){e.dc(b,c)})};
function Cd(a){return Ra(a,function(a){return a.j()&&xd(a.j())})}
function Dd(a,b){if(a.o){var c=b.keys(),d=a.o,e=function(d){"ok"!==d?(Tb("on() or once() for "+b.path().toString()+" failed: "+d),b&&tc(b,function(a,b){for(var c=0;c<b.ma.length;c++){var d=b.ma[c];d.cancel&&(d.aa?v(d.cancel,d.aa):d.cancel)()}}),Fd(a,b)):jb(c,function(a){(a=b.get(a))&&nd(a)})},g=b.toString(),h=b.path().toString();d.ha[h]=d.ha[h]||{};z(!d.ha[h][g],"listen() called twice for same path/queryId.");d.ha[h][g]={$a:b.$a(),C:e};d.X&&Sc(d,h,g,b.$a(),e);return v(a.o.md,a.o,b.path(),b.toString(),
b.$a())}return ca}Bd.prototype.lb=function(a,b,c,d){var e={};tc(b,function(b,h){var i=h.lb(a,c,d);gc(i,function(a,b){e[b]=a?k:ua(e,b)||o})});c.L()||c.z(function(a){D(e,a)||(e[a]=o)});return e};
function Id(a,b,c,d,e,g){var h=b.path();if(g!==m){var i=[];d.L()||d.z(function(a,b){i.push({path:h.F(a),Ja:b});delete g[a]});gc(g,function(a,b){i.push({path:h.F(b),Ja:P})});return i}var b=a.lb(h,b,d,e),l=P,n=[];gc(b,function(b,g){var h=new I(g);b?l=l.I(g,d.J(h)):n=n.concat(Jd(a,d.J(h),L(c,h),e))});return[{path:h,Ja:l}].concat(n)}
function Kd(a,b,c,d,e){for(var g=L(a.ua,b),h=g.parent(),i=o;!i&&h!==m;){var l=h.j();l!==m&&(wd(l)?i=k:(l=a.lb(b,l,c,d),g=g.name(),ua(l,g)&&(i=k)));g=h;h=h.parent()}if(i)return[{path:b,Ja:c}];h=L(a.ua,b);i=h.j();return i!==m?wd(i)?[{path:b,Ja:c}]:Id(a,i,h,c,d,e):Jd(a,c,h,d)}function Jd(a,b,c,d){var e=c.j();if(e!==m)return wd(e)?[{path:c.path(),Ja:b}]:Id(a,e,c,b,d,m);if(b.L())return[];var g=[];b.z(function(b,e){var l=new I(b);g=g.concat(Jd(a,e,L(c,l),d))});return g};function Ld(a){this.H=a;this.V=oc(a);this.o=new Pc(this.H,v(this.Xb,this),v(this.Vb,this),v(this.sb,this));var b=v(function(){return new lc(this.V,this.o)},this),a=a.toString();nc[a]||(nc[a]=b());this.jd=nc[a];this.Gb=new Oa;this.eb=new cd;this.i=new dd;this.R=new Bd(this.o,this.i.Pa);this.Tc=new cd;this.tc=new Bd(m,this.Tc);Md(this,"connected",o);Md(this,"authenticated",o);this.G=new Zc}r=Ld.prototype;r.toString=function(){return(this.H.Eb?"https://":"http://")+this.H.host};r.name=function(){return this.H.Ya};
r.Xb=function(a,b,c){var d=[],e=m;if(9<=a.length&&a.lastIndexOf(".priority")===a.length-9)a=new I(a.substring(0,a.length-9)),c=T(this.i.Da,a).Jb(b),d.push(a);else if(c){var e=b,a=new I(a),c=T(this.i.Da,a),g;for(g in b){var h=R(b[g]),c=c.I(g,h);d.push(a.F(g))}}else a=new I(a),c=R(b),d.push(a);b=Kd(this.R,a,c,this.i.N,e);e=o;for(g=0;g<b.length;++g){var c=b[g],h=this.i,i=c.path;U(h.Da,i,c.Ja);e=ed(h,i)||e}e&&(a=Nd(this,a));Hd(this.R,a,d)};
r.Vb=function(a){Md(this,"connected",a);if(a===o){this.e("onDisconnectEvents");var b=this,c=[];bd(this.G,new I(""),function(a,e){var g=Kd(b.R,a,e,b.i.N,m);c.push.apply(c,b.i.set(a,g));g=Od(b,a);Nd(b,g);Hd(b.R,g,[a])});gd(this.i,c);this.G=new Zc}};r.sb=function(a){Md(this,"authenticated",a)};function Md(a,b,c){b=new I("/.info/"+b);U(a.Tc,b,R(c));Hd(a.tc,b,[b])}
r.gb=function(a,b,c){this.o.gb(a,function(a,c){X(b,a,c)},function(a,b){Tb("auth() was canceled: "+b);if(c){var g=Error(b);g.code=a.toUpperCase();c(g)}})};r.Ib=function(){this.o.Ib()};r.bb=function(a,b,c,d){this.e("set",{path:a.toString(),value:b});var b=R(b,c),c=Kd(this.R,a,b,this.i.N,m),e=this.i.set(a,c),g=this;this.o.put(a.toString(),b.W(k),function(b){var c="ok"===b;gd(g.i,e);c||(Tb("set at "+a+" failed: "+b),ed(g.i,a),c=Nd(g,a),Hd(g.R,c,[]));X(d,b)});b=Od(this,a);Nd(this,b);Hd(this.R,b,[a])};
r.update=function(a,b,c){this.e("update",{path:a.toString(),value:b});var d=T(this.i.Pa,a),e=k,g=[],h;for(h in b){var e=o,i=R(b[h]),d=d.I(h,i);g.push(a.F(h))}if(e)Ob("update() called with empty data.  Don't do anything."),X(c,"ok");else{var d=Kd(this.R,a,d,this.i.N,b),l=this.i.set(a,d),n=this;Xc(this.o,"m",a.toString(),b,function(b){z("ok"===b||"permission_denied"===b,"merge at "+a+" failed.");gd(n.i,l);X(c,b)},j);b=Od(this,a);Nd(this,b);Hd(n.R,b,g)}};
r.Ec=function(a,b,c){this.e("setPriority",{path:a.toString(),Aa:b});var d=T(this.i.N,a).Jb(b),d=Kd(this.R,a,d,this.i.N,m),e=this.i.set(a,d),g=this;this.o.put(a.toString()+"/.priority",b,function(a){gd(g.i,e);X(c,a)});a=Nd(this,a);Hd(g.R,a,[])};r.xc=function(a,b){var c=this;this.o.xc(a.toString(),function(d){"ok"===d&&ad(c.G,a);X(b,d)})};function Pd(a,b,c,d){var e=R(c);Vc(a.o,b.toString(),e.W(k),function(c){"ok"===c&&$c(a.G,b,e);X(d,c)})}
function Qd(a){jc(a.V,"deprecated_on_disconnect");a.jd.Hc.deprecated_on_disconnect=k}r.Lb=function(a,b,c,d,e){".info"===F(a.path)?this.tc.Lb(a,b,c,d,e):this.R.Lb(a,b,c,d,e)};r.hc=function(a,b,c,d){if(".info"===F(a.path))this.tc.hc(a,b,c,d);else if(b=this.R.hc(a,b,c,d),b!==m){for(var c=this.i,a=a.path,d=[],e=0;e<b.length;++e)d[e]=T(c.Da,b[e]);U(c.Da,a,P);for(e=0;e<b.length;++e)U(c.Da,b[e],d[e])}};r.Wa=function(){this.o.Wa()};r.Cb=function(){this.o.Cb()};
r.Fc=function(a){if("undefined"!==typeof console){a?(this.jc||(this.jc=new kc(this.V)),a=this.jc.get()):a=this.V.get();var b=a,c=[],d=0,e;for(e in b)c[d++]=e;var g=function(a,b){return Math.max(b.length,a)};if(c.reduce)e=c.reduce(g,0);else{var h=0;jb(c,function(a){h=g.call(j,h,a)});e=h}for(var i in a){b=a[i];for(c=i.length;c<e+2;c++)i+=" ";console.log(i+b)}}};r.Gc=function(a){jc(this.V,a);this.jd.Hc[a]=k};r.e=function(){Ob("r:"+this.o.id+":",arguments)};
function X(a,b,c){if(a)if("ok"==b)a(m,c);else{var d=b=(b||"error").toUpperCase();c&&(d+=": "+c);c=Error(d);c.code=b;a(c)}};function Rd(a,b){var c=b||a.Gb;b||Sd(a,c);if(c.j()!==m){var d=Td(a,c);z(0<d.length);if(2!==d[0].status&&4!==d[0].status){for(var e=c.path(),g=0;g<d.length;g++)z(1===d[g].status,"tryToSendTransactionQueue_: items in queue should all be run."),d[g].status=2,d[g].fd++;c=T(a.i.N,e).hash();U(a.i.N,e,T(a.i.Pa,e));for(var h=T(a.eb,e).W(k),i=Hb(),l={},n=0;n<d.length;n++)d[n].oc&&(l[d[n].path.toString()]=d[n].path);var p=[],s;for(s in l)p.push(l[s]);for(g=0;g<p.length;g++)M(L(a.i.yb,p[g]),i);a.o.put(e.toString(),
h,function(b){a.e("transaction put response",{path:e.toString(),status:b});for(g=0;g<p.length;g++){var c=L(a.i.yb,p[g]),h=c.j();z(h!==m,"sendTransactionQueue_: pendingPut should not be null.");h===i&&(M(c,m),U(a.i.N,p[g],T(a.i.Da,p[g])))}if("ok"===b){b=[];for(g=0;g<d.length;g++)d[g].status=3,d[g].C&&(c=Ud(a,d[g].path),b.push(v(d[g].C,m,m,k,c))),d[g].lc();Sd(a,L(a.Gb,e));Rd(a);for(g=0;g<b.length;g++)b[g]()}else{if("datastale"===b)for(g=0;g<d.length;g++)d[g].status=4===d[g].status?5:1;else{Tb("transaction at "+
e+" failed: "+b);for(g=0;g<d.length;g++)d[g].status=5,d[g].mc=b}b=Nd(a,e);Hd(a.R,b,[e])}},c)}}else c.mb()&&c.z(function(b){Rd(a,b)})}
function Nd(a,b){var c=Vd(a,b),d=c.path(),e=Td(a,c);U(a.i.Pa,d,T(a.i.N,d));U(a.eb,d,T(a.i.N,d));if(0!==e.length){for(var g=c=T(a.i.Pa,d),h=[],i=0;i<e.length;i++){var l=Ma(d,e[i].path),n=o,p;z(l!==m,"rerunTransactionsUnderNode_: relativePath should not be null.");if(5===e[i].status)n=k,p=e[i].mc;else if(1===e[i].status)if(25<=e[i].fd)n=k,p="maxretry";else{var s=e[i].update(c.J(l).W());t(s)?(Aa("transaction failed: Data returned ",s),s=R(s),c=c.Fa(l,s),e[i].oc&&(g=g.Fa(l,s))):(n=k,p="nodata")}n&&(e[i].lc(),
e[i].status=3,e[i].C&&(n=new W(a,e[i].path),l=new S(c.J(l),n),"nodata"===p?h.push(v(e[i].C,m,m,o,l)):h.push(v(e[i].C,m,Error(p),o,l))))}p=T(a.i.N,d).k();c=c.Jb(p);g=g.Jb(p);U(a.eb,d,c);U(a.i.Pa,d,g);for(i=0;i<h.length;i++)h[i]();Rd(a)}return d}function Vd(a,b){for(var c,d=a.Gb;(c=F(b))!==m&&d.j()===m;)d=L(d,c),b=J(b);return d}function Td(a,b){var c=[];Wd(a,b,c);c.sort(function(a,b){return a.ad-b.ad});return c}
function Wd(a,b,c){var d=b.j();if(d!==m)for(var e=0;e<d.length;e++)c.push(d[e]);b.z(function(b){Wd(a,b,c)})}function Sd(a,b){var c=b.j();if(c){for(var d=0,e=0;e<c.length;e++)3!==c[e].status&&(c[d]=c[e],d++);c.length=d;M(b,0<c.length?c:m)}b.z(function(b){Sd(a,b)})}function Od(a,b){var c=Vd(a,b).path(),d=L(a.Gb,b);Ra(d,function(a){Xd(a)});Xd(d);Qa(d,function(a){Xd(a)});return c}
function Xd(a){var b=a.j();if(b!==m){for(var c=[],d=-1,e=0;e<b.length;e++)4!==b[e].status&&(2===b[e].status?(z(d===e-1,"All SENT items should be at beginning of queue."),d=e,b[e].status=4,b[e].mc="set"):(z(1===b[e].status),b[e].lc(),b[e].C&&c.push(v(b[e].C,m,Error("set"),o,m))));-1===d?M(a,m):b.length=d+1;for(e=0;e<c.length;e++)c[e]()}}function Ud(a,b){var c=new W(a,b);return new S(T(a.eb,b),c)};function Y(){this.ab={}}Y.yd=function(){return Y.Uc?Y.Uc:Y.Uc=new Y};Y.prototype.Wa=function(){for(var a in this.ab)this.ab[a].Wa()};Y.prototype.interrupt=Y.prototype.Wa;Y.prototype.Cb=function(){for(var a in this.ab)this.ab[a].Cb()};Y.prototype.resume=Y.prototype.Cb;var Z={zd:function(a){var b=Q.prototype.hash;Q.prototype.hash=a;var c=Zb.prototype.hash;Zb.prototype.hash=a;return function(){Q.prototype.hash=b;Zb.prototype.hash=c}}};Z.hijackHash=Z.zd;Z.La=function(a){return a.La()};Z.queryIdentifier=Z.La;Z.Bd=function(a){return a.w.o.ha};Z.listens=Z.Bd;Z.Hd=function(a){return a.w.o.Ab};Z.refConnection=Z.Hd;Z.od=Pc;Z.DataConnection=Z.od;Pc.prototype.sendRequest=Pc.prototype.Ca;Pc.prototype.interrupt=Pc.prototype.Wa;Z.pd=Jc;Z.RealTimeConnection=Z.pd;
Jc.prototype.sendRequest=Jc.prototype.Dc;Jc.prototype.close=Jc.prototype.close;Z.nd=qb;Z.ConnectionTarget=Z.nd;Z.wd=function(){Ac=wc=k};Z.forceLongPolling=Z.wd;Z.xd=function(){Bc=k};Z.forceWebSockets=Z.xd;Z.Md=function(a,b){a.w.o.Bc=b};Z.setSecurityDebugCallback=Z.Md;Z.Fc=function(a,b){a.w.Fc(b)};Z.stats=Z.Fc;Z.Gc=function(a,b){a.w.Gc(b)};Z.statsIncrementCounter=Z.Gc;function $(a,b,c){this.Bb=a;this.Q=b;this.ya=c}$.prototype.cancel=function(a){A("Firebase.onDisconnect().cancel",0,1,arguments.length);C("Firebase.onDisconnect().cancel",1,a,k);this.Bb.xc(this.Q,a)};$.prototype.cancel=$.prototype.cancel;$.prototype.remove=function(a){A("Firebase.onDisconnect().remove",0,1,arguments.length);E("Firebase.onDisconnect().remove",this.Q);C("Firebase.onDisconnect().remove",1,a,k);Pd(this.Bb,this.Q,m,a)};$.prototype.remove=$.prototype.remove;
$.prototype.set=function(a,b){A("Firebase.onDisconnect().set",1,2,arguments.length);E("Firebase.onDisconnect().set",this.Q);za("Firebase.onDisconnect().set",a,o);C("Firebase.onDisconnect().set",2,b,k);Pd(this.Bb,this.Q,a,b)};$.prototype.set=$.prototype.set;
$.prototype.bb=function(a,b,c){A("Firebase.onDisconnect().setWithPriority",2,3,arguments.length);E("Firebase.onDisconnect().setWithPriority",this.Q);za("Firebase.onDisconnect().setWithPriority",a,o);Ea("Firebase.onDisconnect().setWithPriority",2,b,o);C("Firebase.onDisconnect().setWithPriority",3,c,k);(".length"===this.ya||".keys"===this.ya)&&f("Firebase.onDisconnect().setWithPriority failed: "+this.ya+" is a read-only object.");var d=this.Bb,e=this.Q,g=R(a,b);Vc(d.o,e.toString(),g.W(k),function(a){"ok"===
a&&$c(d.G,e,g);X(c,a)})};$.prototype.setWithPriority=$.prototype.bb;
$.prototype.update=function(a,b){A("Firebase.onDisconnect().update",1,2,arguments.length);E("Firebase.onDisconnect().update",this.Q);Da("Firebase.onDisconnect().update",a);C("Firebase.onDisconnect().update",2,b,k);var c=this.Bb,d=this.Q,e=k,g;for(g in a)e=o;if(e)Ob("onDisconnect().update() called with empty data.  Don't do anything."),X(b,k);else{e=c.o;g=d.toString();var h=function(e){if("ok"===e)for(var g in a){var h=R(a[g]);$c(c.G,d.F(g),h)}X(b,e)};e.X?Wc(e,"om",g,a,h):e.tb.push({Ac:g,action:"om",
data:a,C:h})}};$.prototype.update=$.prototype.update;var Yd,Zd=0,$d=[];Yd=function(){var a=(new Date).getTime()+Wb,b=a===Zd;Zd=a;for(var c=Array(8),d=7;0<=d;d--)c[d]="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(a%64),a=Math.floor(a/64);z(0===a);a=c.join("");if(b){for(d=11;0<=d&&63===$d[d];d--)$d[d]=0;$d[d]++}else for(d=0;12>d;d++)$d[d]=Math.floor(64*Math.random());for(d=0;12>d;d++)a+="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt($d[d]);z(20===a.length,"NextPushId: Length should be 20.");return a};function W(){var a,b,c;if(arguments[0]instanceof Ld)c=arguments[0],a=arguments[1];else{A("new Firebase",1,2,arguments.length);var d=arguments[0];b=a="";var e=k,g="";if(u(d)){var h=d.indexOf("//");if(0<=h)var i=d.substring(0,h-1),d=d.substring(h+2);h=d.indexOf("/");-1===h&&(h=d.length);a=d.substring(0,h);var d=d.substring(h+1),l=a.split(".");if(3==l.length){h=l[2].indexOf(":");e=0<=h?"https"===i:k;if("firebase"===l[1])Sb(a+" is no longer supported. Please use <YOUR FIREBASE>.firebaseio.com instead");
else{b=l[0];g="";d=("/"+d).split("/");for(i=0;i<d.length;i++)if(0<d[i].length){h=d[i];try{h=decodeURIComponent(h.replace(/\+/g," "))}catch(n){}g+="/"+h}}b=b.toLowerCase()}else b=m}e||"undefined"!==typeof window&&(window.location&&window.location.protocol&&-1!==window.location.protocol.indexOf("https:"))&&Tb("Insecure Firebase access from a secure page. Please use https in calls to new Firebase().");a=new qb(a,e,b);b=new I(g);e=b.toString();if(!(d=!u(a.host)))if(!(d=0===a.host.length))if(!(d=!ya(a.Ya)))if(d=
0!==e.length)e&&(e=e.replace(/^\/*\.info(\/|$)/,"/")),d=!(u(e)&&0!==e.length&&!xa.test(e));d&&f(Error(B("new Firebase",1,o)+'must be a valid firebase URL and the path can\'t contain ".", "#", "$", "[", or "]".'));arguments[1]?arguments[1]instanceof Y?c=arguments[1]:f(Error("Expected a valid Firebase.Context for second argument to new Firebase()")):c=Y.yd();e=a.toString();d=ua(c.ab,e);d||(d=new Ld(a),c.ab[e]=d);c=d;a=b}G.call(this,c,a)}ja(W,G);var ae=W,be=["Firebase"],ce=ba;
!(be[0]in ce)&&ce.execScript&&ce.execScript("var "+be[0]);for(var de;be.length&&(de=be.shift());)!be.length&&t(ae)?ce[de]=ae:ce=ce[de]?ce[de]:ce[de]={};module.exports=W;W.prototype.name=function(){A("Firebase.name",0,0,arguments.length);return this.path.f()?m:La(this.path)};W.prototype.name=W.prototype.name;
W.prototype.F=function(a){A("Firebase.child",1,1,arguments.length);if(fa(a))a=String(a);else if(!(a instanceof I))if(F(this.path)===m){var b=a;b&&(b=b.replace(/^\/*\.info(\/|$)/,"/"));Ha("Firebase.child",b)}else Ha("Firebase.child",a);return new W(this.w,this.path.F(a))};W.prototype.child=W.prototype.F;W.prototype.parent=function(){A("Firebase.parent",0,0,arguments.length);var a=this.path.parent();return a===m?m:new W(this.w,a)};W.prototype.parent=W.prototype.parent;
W.prototype.root=function(){A("Firebase.ref",0,0,arguments.length);for(var a=this;a.parent()!==m;)a=a.parent();return a};W.prototype.root=W.prototype.root;W.prototype.toString=function(){A("Firebase.toString",0,0,arguments.length);var a;if(this.parent()===m)a=this.w.toString();else{a=this.parent().toString()+"/";var b=this.name();a+=encodeURIComponent(String(b))}return a};W.prototype.toString=W.prototype.toString;
W.prototype.set=function(a,b){A("Firebase.set",1,2,arguments.length);E("Firebase.set",this.path);za("Firebase.set",a,o);C("Firebase.set",2,b,k);return this.w.bb(this.path,a,m,b)};W.prototype.set=W.prototype.set;W.prototype.update=function(a,b){A("Firebase.update",1,2,arguments.length);E("Firebase.update",this.path);Da("Firebase.update",a);C("Firebase.update",2,b,k);return this.w.update(this.path,a,b)};W.prototype.update=W.prototype.update;
W.prototype.bb=function(a,b,c){A("Firebase.setWithPriority",2,3,arguments.length);E("Firebase.setWithPriority",this.path);za("Firebase.setWithPriority",a,o);Ea("Firebase.setWithPriority",2,b,o);C("Firebase.setWithPriority",3,c,k);(".length"===this.name()||".keys"===this.name())&&f("Firebase.setWithPriority failed: "+this.name()+" is a read-only object.");return this.w.bb(this.path,a,b,c)};W.prototype.setWithPriority=W.prototype.bb;
W.prototype.remove=function(a){A("Firebase.remove",0,1,arguments.length);E("Firebase.remove",this.path);C("Firebase.remove",1,a,k);this.set(m,a)};W.prototype.remove=W.prototype.remove;
W.prototype.transaction=function(a,b,c){function d(){}A("Firebase.transaction",1,3,arguments.length);E("Firebase.transaction",this.path);C("Firebase.transaction",1,a,o);C("Firebase.transaction",2,b,k);t(c)&&"boolean"!=typeof c&&f(Error(B("Firebase.transaction",3,k)+"must be a boolean."));(".length"===this.name()||".keys"===this.name())&&f("Firebase.transaction failed: "+this.name()+" is a read-only object.");"undefined"===typeof c&&(c=k);var e=this.w,g=this.path,h=c;e.e("transaction on "+g);var i=
new W(e,g);i.vc("value",d);var h={path:g,update:a,C:b,status:m,ad:Hb(),oc:h,fd:0,lc:function(){i.Ub("value",d)},mc:m},l=h.update(T(e.eb,g).W());if(t(l)){Aa("transaction failed: Data returned ",l);h.status=1;var n=L(e.Gb,g),p=n.j()||[];p.push(h);M(n,p);n=T(e.i.N,g).k();U(e.eb,g,R(l,n));h.oc&&(U(e.i.Pa,g,R(l,n)),Hd(e.R,g,[g]));Rd(e)}else h.lc(),h.C&&(e=Ud(e,g),h.C(m,o,e))};W.prototype.transaction=W.prototype.transaction;
W.prototype.Ec=function(a,b){A("Firebase.setPriority",1,2,arguments.length);E("Firebase.setPriority",this.path);Ea("Firebase.setPriority",1,a,o);C("Firebase.setPriority",2,b,k);this.w.Ec(this.path,a,b)};W.prototype.setPriority=W.prototype.Ec;W.prototype.push=function(a,b){A("Firebase.push",0,2,arguments.length);E("Firebase.push",this.path);za("Firebase.push",a,k);C("Firebase.push",2,b,k);var c=Yd(),c=this.F(c);"undefined"!==typeof a&&a!==m&&c.set(a,b);return c};W.prototype.push=W.prototype.push;
W.prototype.ja=function(){return new $(this.w,this.path,this.name())};W.prototype.onDisconnect=W.prototype.ja;W.prototype.Id=function(){Tb("FirebaseRef.removeOnDisconnect() being deprecated. Please use FirebaseRef.onDisconnect().remove() instead.");this.ja().remove();Qd(this.w)};W.prototype.removeOnDisconnect=W.prototype.Id;W.prototype.Ld=function(a){Tb("FirebaseRef.setOnDisconnect(value) being deprecated. Please use FirebaseRef.onDisconnect().set(value) instead.");this.ja().set(a);Qd(this.w)};
W.prototype.setOnDisconnect=W.prototype.Ld;W.prototype.gb=function(a,b,c){A("Firebase.auth",1,3,arguments.length);u(a)||f(Error(B("Firebase.auth",1,o)+"must be a valid credential (a string)."));C("Firebase.auth",2,b,k);C("Firebase.auth",3,b,k);this.w.gb(a,b,c)};W.prototype.auth=W.prototype.gb;W.prototype.Ib=function(){this.w.Ib()};W.prototype.unauth=W.prototype.Ib;
function Pb(a,b){z(!b||a===k||a===o,"Can't turn on custom loggers persistently.");a===k?("undefined"!==typeof console&&("function"===typeof console.log?Mb=v(console.log,console):"object"===typeof console.log&&(Mb=function(a){console.log(a)})),b&&O.setItem("logging_enabled","true")):a?Mb=a:(Mb=m,O.removeItem("logging_enabled"))}W.enableLogging=Pb;W.INTERNAL=Z;W.Context=Y;
